name: Deploy on Push

concurrency: 
  group: production
  cancel-in-progress: true

on:
  push: 
    branches: 
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to BOL Webspace
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Git Repo
      uses: actions/checkout@v2

    - name: Use NodeJS 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: Build Project with Parcel
      run: |
        npm ci
        npm run build
    
    - name: Deploy to BOL Webspace FTP Server
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: webspace.bol.ucla.edu
        protocol: ftps
        username: chrismilan 
        password: ${{ secrets.ftp_password }}
        local-dir: dist/

